"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
require("electron");
require("child_process");
require("fs");
require("path");
require("os");
require("electron-store");
const main = require("./main-Beqs_Wy9.js");
exports.applyCustomerDisplay = main.applyCustomerDisplay;
